// Generation-side page manifests for "Nibs and the Absolutely Perfect Acorn".
// Mirrors the manifests in book.ts (kept in sync by hand). Used ONLY by the image
// generation script (Node cannot import the .ts app source directly).
//
// The prompt is DERIVED from these manifests by the compiler in generate.mjs.

const forbiddenAlways = [
  'any text, words, letters, numbers, or title in the image',
  'frightening or dark imagery',
  'human characters',
  'Nibs wearing clothing',
]

export const CHARACTER_REFS = {
  nibs: 'characters/nibs.png',
  tilly: 'characters/Tilly.png',
}

export const pages = [
  {
    page: 1,
    charactersPresent: ['nibs'],
    location: 'a bright woodland clearing floor scattered with acorns',
    timeOfDay: 'morning',
    action: 'Nibs sits among several acorns, inspecting one closely and frowning with great seriousness, a small pile of rejected acorns beside him',
    emotionalBeat: 'fussy, particular, self-important',
    requiredVisualFacts: ['several ordinary acorns on the ground', 'Nibs holding one acorn up to inspect it', 'a small pile of set-aside acorns'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a sprout or seedling', 'Tilly the owl'],
    composition: 'Nibs centered-low, acorns around him, warm morning light',
  },
  {
    page: 2,
    charactersPresent: ['nibs'],
    location: 'the woodland clearing, one bright patch of sunlight on the ground',
    timeOfDay: 'morning',
    action: 'Nibs holds up a single flawless acorn in both paws, eyes wide with wonder, a beam of sunlight on it',
    emotionalBeat: 'awe and joy',
    requiredVisualFacts: ['one single perfect acorn held reverently in both paws', 'a warm shaft of sunlight highlighting the acorn', 'Nibs looking amazed'],
    forbiddenVisualFacts: [...forbiddenAlways, 'many acorns', 'a sprout or seedling', 'Tilly the owl'],
    composition: 'close, tender, the acorn is the focal point',
  },
  {
    page: 3,
    charactersPresent: ['nibs'],
    location: 'the woodland clearing',
    timeOfDay: 'morning',
    action: 'Nibs clutches the acorn to his chest and glances over his shoulder with sudden worry, as if someone might be watching',
    emotionalBeat: 'joy tipping into worry',
    requiredVisualFacts: ['Nibs holding the acorn protectively against his chest', 'a wary, worried expression', 'glancing over his shoulder'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a sprout or seedling', 'Tilly the owl', 'an actual threat or predator'],
    composition: 'Nibs slightly hunched and protective, clearing quiet behind him',
  },
  {
    page: 4,
    charactersPresent: ['nibs'],
    location: 'the base of a large crooked tree root in the clearing',
    timeOfDay: 'midday',
    action: 'Nibs pats fresh earth over a spot beneath a crooked root with his paws, focused and secretive',
    emotionalBeat: 'earnest, industrious, secretive',
    requiredVisualFacts: ['a distinctive crooked tree root', 'freshly patted earth', 'Nibs working with his paws in the dirt'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a sprout or seedling', 'Tilly the owl'],
    composition: 'the crooked root prominent (recurring landmark), Nibs low beside it',
  },
  {
    page: 5,
    charactersPresent: ['nibs'],
    location: 'the clearing, now dotted with several small patches of dug earth',
    timeOfDay: 'afternoon',
    action: 'Nibs stands proudly amid a ridiculous number of little dig-marks, holding a scrappy hand-drawn map, several other marked spots around him',
    emotionalBeat: 'proud of an absurdly elaborate plan',
    requiredVisualFacts: ['many small patches of disturbed earth across the clearing', 'Nibs holding a crude little map with only scribbles and arrows, no readable text', 'an over-serious, satisfied expression'],
    forbiddenVisualFacts: ['frightening or dark imagery', 'human characters', 'Nibs wearing clothing', 'readable words or letters on the map', 'a sprout or seedling', 'Tilly the owl'],
    composition: 'wide enough to show the comic sprawl of dig-marks; Nibs central and pleased',
  },
  {
    page: 6,
    charactersPresent: ['nibs', 'tilly'],
    location: 'the clearing with the dig-marks, a low branch above',
    timeOfDay: 'late afternoon',
    action: 'Tilly the owl perches on a low branch tilting her head with gentle curiosity; Nibs stands below, caught mid-thought, one paw raised, suddenly uncertain',
    emotionalBeat: 'a quiet, puncturing question; dawning uncertainty',
    requiredVisualFacts: ['Tilly the brown owl perched on a low branch, head tilted, calm and curious', 'Nibs looking up, caught off guard and uncertain', 'the dig-marked clearing visible'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a sprout or seedling'],
    composition: 'two-character: Tilly upper-right on branch, Nibs lower-left; both on-model; similar small scale',
  },
  {
    page: 7,
    charactersPresent: ['nibs', 'tilly'],
    location: 'the base of the crooked root',
    timeOfDay: 'late afternoon',
    action: 'Nibs stares in horror into an empty hole beneath the crooked root; Tilly leans in beside him looking thoughtful',
    emotionalBeat: 'alarm and disbelief',
    requiredVisualFacts: ['an empty hole in the earth beneath the crooked root', 'Nibs looking shocked and dismayed', 'Tilly observing calmly nearby'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a sprout or seedling', 'the acorn visible'],
    composition: 'both characters focused on the empty hole; the crooked root frames it',
  },
  {
    page: 8,
    charactersPresent: ['nibs', 'tilly'],
    location: 'the clearing, following a trail of small paw prints',
    timeOfDay: 'evening approaching',
    action: 'Nibs crouches like a detective following a line of paw prints that loop back toward himself; Tilly walks behind, glancing between the prints and Nibs',
    emotionalBeat: 'determined but comically wrong; Tilly quietly noticing the truth',
    requiredVisualFacts: ['a line of small squirrel paw prints in the dirt', 'Nibs following the prints with intense focus', 'Tilly noticing that the prints lead back to Nibs'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a sprout or seedling'],
    composition: 'the looping prints visible on the ground; two characters mid-investigation',
  },
  {
    page: 9,
    charactersPresent: ['nibs', 'tilly'],
    location: 'the middle of the dug-up clearing at dusk',
    timeOfDay: 'dusk',
    action: 'Nibs sits slumped and defeated among the dig-marks; Tilly sits close beside him, offering a gentle idea rather than a lecture',
    emotionalBeat: 'low point: quiet defeat, then a gentle reframe',
    requiredVisualFacts: ['Nibs sitting down, deflated, surrounded by his own dig-marks', 'Tilly sitting companionably beside him', 'soft dusk light'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a sprout or seedling'],
    composition: 'intimate two-shot, warm low light, small figures in a big quiet clearing',
  },
  {
    page: 10,
    charactersPresent: ['nibs'],
    location: 'a particular spot in the clearing, away from the crooked root',
    timeOfDay: 'dusk',
    action: 'Nibs digs at one specific spot and uncovers the perfect acorn at last, a look of relief and recognition on his face',
    emotionalBeat: 'realization and relief; he solved it himself',
    requiredVisualFacts: ['Nibs uncovering the acorn from the earth', 'the acorn visible in the freshly opened hole', 'a look of dawning realization on Nibs'],
    forbiddenVisualFacts: [...forbiddenAlways, 'Tilly the owl', 'the acorn sprouting yet'],
    composition: 'Nibs and the just-uncovered acorn as the focal point, dusk glow',
  },
  {
    page: 11,
    charactersPresent: ['nibs'],
    location: 'the spot where he uncovered it, close on his paws',
    timeOfDay: 'dusk',
    action: 'Nibs holds the sprouting acorn: a tiny pale root and first green shoot have split the shell; he pauses, paw hovering, uncertain',
    emotionalBeat: 'dismay turning to something quieter and more thoughtful',
    requiredVisualFacts: ['the acorn with a small pale root and a tiny green sprout emerging from a cracked shell', 'Nibs looking at it closely, paw hovering, hesitating', 'a tender, thoughtful expression'],
    forbiddenVisualFacts: [...forbiddenAlways, 'Tilly the owl', 'a fully grown tree'],
    composition: 'very close on Nibs and the sprouting acorn; the quiet emotional center',
  },
  {
    page: 12,
    charactersPresent: ['nibs'],
    location: 'the spot where he uncovered it, close on the sprout in the earth',
    timeOfDay: 'dusk turning to evening',
    action: 'Nibs gently pats soft earth back around the tiny sprouted acorn with both paws, looking at it with a soft, accepting expression rather than dismay',
    emotionalBeat: 'the quiet turn: letting go of "perfect" and choosing to let it grow',
    requiredVisualFacts: ['the little sprouted acorn set in the earth with its tiny green shoot', 'Nibs patting the soil around it with both paws', 'a gentle, accepting expression on Nibs'],
    forbiddenVisualFacts: [...forbiddenAlways, 'Tilly the owl', 'a fully grown tree', 'a fence or barrier yet'],
    composition: 'close and tender, warm low evening light; Nibs and the sprout share the frame',
  },
  {
    page: 13,
    charactersPresent: ['nibs', 'tilly'],
    location: 'the clearing next morning, a small fenced-off patch of earth with the sprout',
    timeOfDay: 'morning',
    action: 'Nibs stands guard proudly beside a tiny sprout he has ringed with an absurdly elaborate little twig fence (with a tiny gate, and a second smaller fence inside the first); Tilly watches from a branch with a knowing, amused look',
    emotionalBeat: 'affectionate comic callback: he is still exactly himself',
    requiredVisualFacts: ['a tiny green sprout in a patch of earth', 'an absurdly elaborate little twig fence ringing the sprout (a tiny gate, and a second smaller fence inside the first)', 'Nibs standing guard proudly', 'Tilly watching with a knowing, amused expression'],
    forbiddenVisualFacts: ['frightening or dark imagery', 'human characters', 'Nibs wearing clothing', 'readable words or letters anywhere in the image', 'any sign, signpost, board, placard, or plaque', 'a fully grown tree'],
    composition: 'morning light, comic reversal; Nibs proudly guarding the over-fenced sprout, Tilly observing from a branch',
  },
]
