// Generation-side page manifests for "Pip and the First Flame".
// Mirrors the manifests in book.ts (kept in sync by hand). Used ONLY by the image
// generation script. Prompt is DERIVED from these by scripts/generate-book.mjs.

const forbiddenAlways = [
  'any text, words, letters, numbers, or title in the image',
  'any sign, signpost, board, placard, label, or plaque',
  'frightening or dark imagery',
  'Pip wearing clothing',
  'a different dragon; Pip changing color or losing his cream belly, horns, or small orange wings',
]

export const CHARACTER_REFS = {
  pip: 'characters/pip.png',
}

export const CHARACTER_BIOS = {
  pip:
    'Pip, a small cute baby dragon: warm red scaled body with a soft cream / pale-gold belly and chest, a row of small dark-red curved horns and spines down his head and back, big expressive amber-brown eyes, small orange bat-like wings with a lighter membrane, four little clawed feet and a long ridged tail; a gentle, friendly, kind face',
}

export const pages = [
  {
    page: 1,
    charactersPresent: ['pip'],
    location: 'a warm fantasy valley at dusk, a village of little dragon homes with unlit paper lanterns strung between them, mountains and a far castle',
    timeOfDay: 'early evening, soft golden dusk',
    action: 'Pip the small red dragon sits on a rock looking up at rows of paper lanterns waiting to be lit, hopeful and a little wistful',
    emotionalBeat: 'gentle longing; the night is special and Pip wants to belong to it',
    requiredVisualFacts: ['Pip the small red dragon with cream belly, small horns, and little orange wings', 'strings of unlit paper lanterns above a cozy valley village', 'warm dusk light'],
    forbiddenVisualFacts: [...forbiddenAlways, 'visible fire or flames yet', 'other dragons crowding the frame'],
    composition: 'Pip lower-center looking up, lanterns arcing overhead, valley behind; warm and inviting',
  },
  {
    page: 2,
    charactersPresent: ['pip'],
    location: 'the same rock in the valley village',
    timeOfDay: 'dusk',
    action: 'Pip puffs his cheeks and breathes out hard, producing only a small wisp of grey smoke, looking cross-eyed at it',
    emotionalBeat: 'earnest effort, comic disappointment',
    requiredVisualFacts: ['Pip breathing out a small curl of grey smoke (no fire)', 'puffed cheeks and a determined face', 'the cozy village behind'],
    forbiddenVisualFacts: [...forbiddenAlways, 'actual flames or fire', 'scary imagery'],
    composition: 'close on Pip and the little wisp of smoke; warm dusk',
  },
  {
    page: 3,
    charactersPresent: ['pip'],
    location: 'the valley village clearing',
    timeOfDay: 'dusk',
    action: 'Pip stands on tiptoe with eyes squeezed shut and cheeks puffed, straining comically to breathe fire, a small puff of smoke escaping',
    emotionalBeat: 'trying too hard; forcing it',
    requiredVisualFacts: ['Pip straining with eyes shut and puffed cheeks', 'only a puff of smoke', 'a comic, effortful pose'],
    forbiddenVisualFacts: [...forbiddenAlways, 'actual flames or fire'],
    composition: 'full-body Pip mid-strain, generous space around him, warm light',
  },
  {
    page: 4,
    charactersPresent: ['pip'],
    location: 'the festival square, glowing lanterns lighting up in the distance',
    timeOfDay: 'evening, growing dark',
    action: 'Pip stands beside his own small unlit paper lantern, watching many warm glowing lanterns light up across the valley beyond him',
    emotionalBeat: 'left out; the quiet ache of being the only one',
    requiredVisualFacts: ['Pip beside a single dark, unlit lantern', 'many warm glowing lanterns in the distance', 'Pips wistful expression'],
    forbiddenVisualFacts: [...forbiddenAlways, 'other dragons shown in clear detail (keep them distant/implied)', 'scary imagery'],
    composition: 'Pip and his dark lantern in the foreground, distant glow behind; gentle contrast',
  },
  {
    page: 5,
    charactersPresent: ['pip'],
    location: 'the shadowy edge of the valley, tall grass, away from the festival glow',
    timeOfDay: 'night',
    action: 'Pip walks alone into soft blue-dark grass at the valleys edge, horns drooping, then pauses, hearing a tiny sound',
    emotionalBeat: 'lonely, then a flicker of curiosity',
    requiredVisualFacts: ['Pip alone in cool blue-toned tall grass at night', 'the festival glow small and far behind him', 'a curious, listening pause'],
    forbiddenVisualFacts: [...forbiddenAlways, 'scary or threatening imagery', 'the glow-moth clearly visible yet'],
    composition: 'small Pip in a large soft-dark space, distant warm glow behind; calm not scary',
  },
  {
    page: 6,
    charactersPresent: ['pip'],
    location: 'the dark grass at the valley edge',
    timeOfDay: 'night',
    action: 'Pip crouches gently over a tiny pale glow-moth sitting in the grass with its glow gone dark, its wings drawn in, shivering',
    emotionalBeat: 'tender concern for something smaller than himself',
    requiredVisualFacts: ['a tiny pale glow-moth with its light gone out, sitting small in the grass', 'Pip leaning down gently and softly', 'a caring, worried expression on Pip'],
    forbiddenVisualFacts: [...forbiddenAlways, 'the moth glowing brightly yet', 'scary imagery'],
    composition: 'close, tender two-shot of Pip and the small dark moth; soft night',
  },
  {
    page: 7,
    charactersPresent: ['pip'],
    location: 'the dark grass',
    timeOfDay: 'night',
    action: 'Pip curls his body and wings gently around the tiny moth cupped in his paws, sheltering it from the wind, speaking softly to it',
    emotionalBeat: 'pure kindness; caring with his whole heart',
    requiredVisualFacts: ['Pip curled protectively around the tiny moth cupped in his paws', 'his little wings sheltering it', 'a gentle, loving expression'],
    forbiddenVisualFacts: [...forbiddenAlways, 'flames', 'scary imagery'],
    composition: 'intimate, warm-cool blend; Pip wrapped around the tiny moth, centered with headroom',
  },
  {
    page: 8,
    charactersPresent: ['pip'],
    location: 'the dark grass',
    timeOfDay: 'night',
    action: 'A soft warm glow begins to shine from within Pips chest and cupped paws, lighting his face gently as he cradles the moth; he looks surprised and moved',
    emotionalBeat: 'wonder; warmth arriving quietly from the inside',
    requiredVisualFacts: ['a soft warm glow coming from within Pips chest and paws', 'the gentle light on Pips surprised, tender face', 'the moth cradled safely'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a big or scary blaze of fire', 'burning or danger'],
    composition: 'the inner glow is the light source; Pip centered, soft warm halo, generous margin',
  },
  {
    page: 9,
    charactersPresent: ['pip'],
    location: 'the dark grass',
    timeOfDay: 'night',
    action: 'Pip breathes out gently and a small bright warm flame appears softly at the tip of his snout, lighting up his amazed happy face',
    emotionalBeat: 'joyful astonishment; his first flame, born of warmth',
    requiredVisualFacts: ['a small, gentle, bright flame at the tip of Pips nose', 'Pips amazed and delighted face lit by it', 'the little moth nearby, warmed'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a large or frightening fire', 'anything burning or dangerous'],
    composition: 'the small flame as the warm focal point; Pip centered with headroom, soft night around',
  },
  {
    page: 10,
    charactersPresent: ['pip'],
    location: 'the grass at the valley edge',
    timeOfDay: 'night',
    action: 'The little moth glows golden again and lifts up into the air, glowing happily, while Pip watches with delight, his small flame still warm',
    emotionalBeat: 'relief and shared joy; the kindness returned as light',
    requiredVisualFacts: ['the glow-moth now glowing warm gold and flying up happily', 'Pip watching with a joyful face', 'gentle warm light in the dark'],
    forbiddenVisualFacts: [...forbiddenAlways, 'scary imagery', 'large fire'],
    composition: 'the rising glowing moth draws the eye upward; Pip below watching, warm and happy',
  },
  {
    page: 11,
    charactersPresent: ['pip'],
    location: 'back at the festival, at Pips own small lantern',
    timeOfDay: 'night',
    action: 'Pip leans toward his own paper lantern and lights it softly with his small nose-flame; the lantern glows warmly to life',
    emotionalBeat: 'quiet pride; doing it his own gentle way',
    requiredVisualFacts: ['Pip gently lighting his own paper lantern with a small flame', 'the lantern glowing warmly to life', 'Pips calm, proud, happy face'],
    forbiddenVisualFacts: [...forbiddenAlways, 'a big blaze', 'scary imagery'],
    composition: 'warm pool of new lantern light on Pip; centered, cozy, headroom above',
  },
  {
    page: 12,
    charactersPresent: ['pip'],
    location: 'the festival, Pips glowing lantern beside him, other lanterns warm in the distance',
    timeOfDay: 'night',
    action: 'Pip sits proudly and happily beside his own softly glowing lantern, the little glow-moth hovering near him, the valley full of warm lantern light',
    emotionalBeat: 'warm, complete belonging; small but truly his',
    requiredVisualFacts: ['Pip beside his own warmly glowing lantern', 'the friendly glow-moth glowing near him', 'many warm lanterns across the happy valley'],
    forbiddenVisualFacts: [...forbiddenAlways, 'scary imagery', 'a giant fire'],
    composition: 'warm, full, festive glow; Pip and his lantern centered, the valley bright behind',
  },
  {
    page: 13,
    charactersPresent: ['pip'],
    location: 'the glowing festival valley, full of warm light',
    timeOfDay: 'night, festive and bright',
    action: 'Pip sits happily among the warm festival glow with the little golden glow-moth resting on his nose, both content, the valley full of lantern light behind',
    emotionalBeat: 'the warm, complete, happy ending: friendship, belonging, a bright future',
    requiredVisualFacts: ['Pip happy and content with the golden glow-moth resting on or near his nose', 'a valley full of warm glowing lanterns', 'a bright, joyful, peaceful mood'],
    forbiddenVisualFacts: [...forbiddenAlways, 'scary imagery', 'a giant fire'],
    composition: 'warm celebratory final image; Pip and the glow-moth centered, festival glow all around, headroom',
  },
]
